---
apiVersion: v1
kind: Service
metadata:
  name: k8s-2-graph-name-neo4j-discovery-public-0
  labels:
    neo4j.com/cluster: graph-name-neo4j
    neo4j.com/role: external-cluster-members
spec:
  publishNotReadyAddresses: true
  type: LoadBalancer
  ports:
    - name: discovery
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: transaction
      port: 6000
      targetPort: 6000
      protocol: TCP
    - name: raft
      port: 7000
      targetPort: 7000
      protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: "k8s-2-graph-name-neo4j-core-0"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-2-graph-name-neo4j-discovery-public-1
  labels:
    neo4j.com/cluster: graph-name-neo4j
    neo4j.com/role: external-cluster-members
spec:
  publishNotReadyAddresses: true
  type: LoadBalancer
  ports:
    - name: discovery
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: transaction
      port: 6000
      targetPort: 6000
      protocol: TCP
    - name: raft
      port: 7000
      targetPort: 7000
      protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: "k8s-2-graph-name-neo4j-core-1"
---