---
apiVersion: v1
kind: Service
metadata:
  name: k8s-1-graph-name-neo4j-bolt-public-0
  labels:
    neo4j.com/cluster: graph-name-neo4j
    neo4j.com/role: external-clients
spec:
  type: LoadBalancer
  ports:
    - name: bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
    - name: http
      port: 7474
      protocol: TCP
      targetPort: 7474
    - name: https
      port: 7473
      protocol: TCP
      targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: "k8s-1-graph-name-neo4j-core-0"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-1-graph-name-neo4j-bolt-public-1
  labels:
    neo4j.com/cluster: graph-name-neo4j
    neo4j.com/role: external-clients
spec:
  type: LoadBalancer
  ports:
    - name: bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
    - name: http
      port: 7474
      protocol: TCP
      targetPort: 7474
    - name: https
      port: 7473
      protocol: TCP
      targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: "k8s-1-graph-name-neo4j-core-1"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-1-graph-name-neo4j-bolt-public-2
  labels:
    neo4j.com/cluster: graph-name-neo4j
    neo4j.com/role: external-clients
spec:
  type: LoadBalancer
  ports:
    - name: bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
    - name: http
      port: 7474
      protocol: TCP
      targetPort: 7474
    - name: https
      port: 7473
      protocol: TCP
      targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: "k8s-1-graph-name-neo4j-core-2"
---